// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHHfWU4VnGkiiKEp_El1hGLAS9Qh1hvfY',
    appId: '1:406014420922:web:4e0487b9cbdbd0b1789f83',
    messagingSenderId: '406014420922',
    projectId: 'round3-restaurant-app',
    authDomain: 'round3-restaurant-app.firebaseapp.com',
    storageBucket: 'round3-restaurant-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_mmRc04cMBBUeUt1f8PWkVahvCor-lo',
    appId: '1:406014420922:android:8f4ba8e5daa05a6e789f83',
    messagingSenderId: '406014420922',
    projectId: 'round3-restaurant-app',
    storageBucket: 'round3-restaurant-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnDahb-fu42o0tRxAZDswLRePRGaqSh48',
    appId: '1:406014420922:ios:ce3d38f865edfd73789f83',
    messagingSenderId: '406014420922',
    projectId: 'round3-restaurant-app',
    storageBucket: 'round3-restaurant-app.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );
}
